# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('TRAVEL', 'Travel'), ('EAT', 'Eat'), ('FEEL', 'Feel'), ('READ', 'Read')], default='FEEL', max_length=6),
        ),
    ]
